spirng:
  application:
    name: mall-config-server
cloud:
  config:
    server:
      git:
        uri: https://github.com/wanghengGit/config-center-for-snailmall
        username: 1012056369@qq.com
        password: *
        search-paths: user-service-config,category-service-config,product-service-config,order-service-config,keygen-service-config,shipping-service-config,cart-service-config,gateway-service-config
server:
  port: 8079
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/

